const dims = { height: 300, width: 300, radius: 150 };
const cent = { x: dims.width / 2 + 5, y: dims.height / 2 + 5 };
const svg = d3
  .select(".canvas")
  .append("svg")
  .attr("width", dims.width + 150)
  .attr("height", dims.height + 150);

const graph = svg
  .append("g")
  .attr("transform", `translate(${cent.x}, ${cent.y})`);

const pie = d3
  .pie()
  .sort(null)
  .value(d => d.cost);

const arcPath = d3
  .arc()
  .outerRadius(dims.radius)
  .innerRadius(dims.radius / 2);

const color = d3.scaleOrdinal(d3["schemeSet3"]);

// legend setup
const legendGroup = svg
  .append("g")
  .attr("transform", `translate(${dims.width + 50}, 30)`);

// use legendColor function from d3 legend package
const legend = d3
  .legendColor()
  .shape("circle")
  .shapePadding(10)
  .scale(color);

// tooltip
const tip = d3
  .tip()
  .attr("class", "tip card")
  .html(d => {
    let content = `<div class="name">${d.data.name}</div>`;
    content += `<div class="cost">$${d.data.cost}</div>`;
    content += `<div class="delete">Click slice to delete</div>`;
    return content;
  });

graph.call(tip);

// update function
const update = data => {
  // 1. Update scales - update color scale domain
  color.domain(data.map(d => d.name));

  // update and call legend
  legendGroup.call(legend);
  legendGroup
    .selectAll("text")
    .attr("fill", "#616161 ")
    .attr("font-weight", 500);

  // 2. Join enhanced (pie) data to path elements
  const paths = graph.selectAll("path").data(pie(data));

  // 3. Remove any unwanted paths using exit selection
  paths
    .exit()
    .transition()
    .duration(750)
    .attrTween("d", arcTweenExit)
    .remove();

  // 4. Update current paths in DOM
  paths
    .attr("d", arcPath)
    .transition()
    .duration(750)
    .attrTween("d", arcTweenUpdate);

  // 5. Append enter selection to DOM
  // we dont have any path elements to begin with, so enter() will contain all virtual path elements
  paths
    .enter()
    .append("path")
    .attr("class", "arc")
    .attr("stroke", "#fff")
    .attr("stroke-width", 3)
    // d refers to the data generated by pie(data)
    .attr("fill", d => color(d.data.name))
    .each(function(d) {
      this._current = d;
    })
    .transition()
    .duration(750)
    .attrTween("d", arcTweenEnter);

  // add event handler on all paths
  graph
    .selectAll("path")
    .on("mouseover", (d, i, n) => {
      // tip expects two parameters, data and the current context of path it is referring to.
      // We could use this, but arrow function binding of this won't work so we use n[i] instead
      tip.show(d, n[i]);
      handleMouseOver(d, i, n);
    })
    .on("mouseout", (d, i, n) => {
      tip.hide();
      handleMouseOut(d, i, n);
    })
    .on("click", handleClick);
};

// data array and firestore
let data = [];

db.collection("expenses").onSnapshot(res => {
  // docChanges contains all changes in database
  res.docChanges().forEach(change => {
    const doc = { ...change.doc.data(), id: change.doc.id };
    // change type can be added, removed, or modified
    switch (change.type) {
      case "added":
        data.push(doc);
        break;
      case "modified":
        const index = data.findIndex(item => item.id === doc.id);
        data[index] = doc;
        break;
      case "removed":
        data = data.filter(item => item.id !== doc.id);
        break;
      default:
        break;
    }
  });

  update(data);
});

const arcTweenEnter = d => {
  let i = d3.interpolate(d.endAngle, d.startAngle);

  return function(t) {
    d.startAngle = i(t);
    return arcPath(d);
  };
};

const arcTweenExit = d => {
  let i = d3.interpolate(d.startAngle, d.endAngle);

  return function(t) {
    d.startAngle = i(t);
    return arcPath(d);
  };
};

// use function keyword to use binding of "this"
function arcTweenUpdate(d) {
  // this._current stores the "old"/current angles
  // d stores the updated angles

  // interpolate between the two objects
  let i = d3.interpolate(this._current, d);
  // update the current prop with updated data
  this._current = i(1);

  return function(t) {
    return arcPath(i(t));
  };
}

// event handlers
// we name the transitions because if it isn't named, d3 will interpret that the hover transitions can be interactive with other transitions,
// which may cause other interactions to interrupt this transition or allow this transition to interrupt other transitions
// n is the selection of all the paths
// i is the index of the element we're currently hovering over
const handleMouseOver = (d, i, n) => {
  d3.select(n[i])
    .transition("changeSliceFill")
    .duration(300)
    .attr("fill", "#ff3d00");
};

const handleMouseOut = (d, i, n) => {
  d3.select(n[i])
    .transition("changeSliceFill")
    .duration(300)
    .attr("fill", d => color(d.data.name));
};

const handleClick = d => {
  const id = d.data.id;
  db.collection("expenses")
    .doc(id)
    .delete();
};
